battles/urls.py
from django.conf.urls import url

from .views import BattlesListView, BattleView, ChoosePokemonTeamView


urlpatterns = [
    url(r'^$|^(create)/$', BattlesListView.as_view(), name='list'),
    url(r'^details/(?P<pk>[\w-]+)$', BattleView.as_view(), name='details'),
    url(r'^details/(?P<pk>[\w-]+)/team$', ChoosePokemonTeamView.as_view(), name='team'),
]

pokebattle/urls.py
from django.conf import settings
from django.conf.urls import include, url  # noqa
from django.contrib import admin
from django.views.generic import TemplateView

import django_js_reverse.views

from battles.views import InviteView


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin/statuscheck/', include('celerybeat_status.urls')),
    url(r'^jsreverse/$', django_js_reverse.views.urls_js, name='js_reverse'),
    url(r'^social/', include('social_django.urls', namespace='social')),

    # Pokebattle
    url(r'^', include('users.urls', namespace='auth')),
    url(r'^$', TemplateView.as_view(template_name='common/index.html'), name='home'),
    url(r'^battles/', include('battles.urls', namespace='battles')),
    url(r'^invite/$', InviteView.as_view(), name='invite'),

    # API
    url(r'api/', include('battles.endpoints_urls', namespace='api-battles')),
    url(r'api/', include('users.endpoints_urls', namespace='api-users')),
    url(r'api/', include('pokemons.endpoints_urls', namespace='api-pokemon')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url

from .views import UserInvitedProcessView, UserLoginView, UserLogoutView, UserSignupView


urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),
    url(r'^signup/$', UserSignupView.as_view(), name='signup'),
    url(r'^invite/validate$', UserInvitedProcessView.as_view(), name='validate-invite')
]

battles/models.py
from django.db import models

from common.models import IndexedTimeStampedModel
from pokemons.models import Pokemon
from users.models import User

from .choices import BATTLE_STATUS


class Battle(models.Model):
    creator = models.ForeignKey(User, related_name='battle_creator')
    opponent = models.ForeignKey(User, related_name='battle_opponent')
    date_created = models.DateTimeField(auto_now_add=True)
    winner = models.ForeignKey(User, related_name='battle_winner', blank=True, null=True)
    status = models.CharField(max_length=2, choices=BATTLE_STATUS, default='O')

    def __str__(self):
        return '{0} vs. {1}'.format(
            self.creator.get_short_name(),
            self.opponent.get_short_name()
        )

    @property
    def status_label(self):
        return self.get_status_display().lower()


class BattleTeam(models.Model):
    battle_related = models.ForeignKey(Battle, related_name='team')
    pokemons = models.ManyToManyField(Pokemon, related_name='battle_team')
    trainer = models.ForeignKey(User, related_name='battle_team')

    class Meta:
        ordering = ['battle_related']

    def __str__(self):
        return '#{0} / {1} / {2}'.format(
            self.battle_related.id,
            list(self.pokemons.all()),
            self.trainer
        )


class Invite(IndexedTimeStampedModel):
    inviter = models.ForeignKey(User, related_name='invites')
    invitee = models.EmailField()
    key = models.CharField('Invitation key', max_length=12, blank=True, null=True, unique=True)
    accepted = models.BooleanField('User has accepted this invite', default=False)

    def __str__(self):
        return 'from {inviter} to {invitee}'.format(
            inviter=self.inviter,
            invitee=self.invitee
        )

battles/forms.py
from django import forms

from dal import autocomplete

from battles.helpers.battle import can_teams_battle
from pokemons.helpers.pokemon import has_team_duplicate_pokemon, pokemon_stats_exceeds_limit
from pokemons.models import Pokemon
from users.models import User

from .models import Battle, BattleTeam, Invite


class CreateBattleForm(forms.ModelForm):
    class Meta:
        model = Battle
        fields = ['opponent']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        users = User.objects.exclude(id=self.initial['creator'])
        self.fields['opponent'].queryset = users


class ChooseTeamForm(forms.ModelForm):
    class Meta:
        model = BattleTeam
        fields = []

    first_pokemon = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='/api/pokemon-autocomplete',
            attrs={
                'data-placeholder': 'Select the first Pokemon',
                'data-html': True
            })
    )

    second_pokemon = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='/api/pokemon-autocomplete',
            attrs={
                'data-placeholder': 'Select the second Pokemon',
                'data-html': True
            })
    )

    third_pokemon = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='/api/pokemon-autocomplete',
            attrs={
                'data-placeholder': 'Select the third Pokemon',
                'data-html': True
            })
    )

    def clean(self):
        cleaned_data = super().clean()

        first_pokemon = cleaned_data.get('first_pokemon')
        second_pokemon = cleaned_data.get('second_pokemon')
        third_pokemon = cleaned_data.get('third_pokemon')
        battle_related = self.initial.get('battle_related')

        team = [first_pokemon, second_pokemon, third_pokemon]

        if None in team:
            raise forms.ValidationError(
                'There are some invalid Pokemon in your team.'
            )

        if has_team_duplicate_pokemon(team):
            raise forms.ValidationError(
                'There are duplicate Pokemon, please use unique ids.'
            )

        if pokemon_stats_exceeds_limit(team):
            raise forms.ValidationError(
                'Your Pokemon stats cannot sum more than 600.'
            )

        existent_team_pokemon = BattleTeam.objects.filter(
            battle_related=battle_related
        ).first()

        if existent_team_pokemon and can_teams_battle(
                existent_team_pokemon.pokemons.all(), team):
            raise forms.ValidationError(
                'Some of your Pokemon already exist in '
                'the opponent\'s team, please pick other ones.'
            )

        return cleaned_data

    def save(self, commit=True):
        first_pokemon = self.cleaned_data.get('first_pokemon')
        second_pokemon = self.cleaned_data.get('second_pokemon')
        third_pokemon = self.cleaned_data.get('third_pokemon')

        team = [first_pokemon, second_pokemon, third_pokemon]
        battle_related = self.initial.get('battle_related')
        trainer = self.initial.get('trainer')

        for pokemon in team:
            pokemon.save()

        new_team = BattleTeam.objects.create(
            battle_related=battle_related,
            trainer=trainer
        )
        new_team.pokemons.add(*team)
        return new_team


class InviteForm(forms.ModelForm):
    class Meta:
        model = Invite
        fields = ['invitee']

    def clean_invitee(self):
        email = self.cleaned_data.get('invitee')
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise forms.ValidationError('This user already exists.')

        invite_exists = Invite.objects.filter(invitee=email).exists()
        if invite_exists:
            raise forms.ValidationError('This person has already been invited!')

        return email

battles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http.response import HttpResponseRedirect
from django.utils.html import format_html
from django.views import generic

from dal import autocomplete

from battles.helpers.battle import process_battle
from battles.helpers.emails import send_battle_invite_email, send_pokebattle_invite_email
from battles.helpers.invites import create_invite_key
from battles.tasks.battle import run_battle_task
from pokemons.models import Pokemon
from users.mixins import UserIsPartOfBattleMixin

from .forms import ChooseTeamForm, CreateBattleForm, InviteForm
from .models import Battle, BattleTeam


# TODO: Remove these old not-React templates


class BattlesListView(LoginRequiredMixin, generic.ListView):
    # template_name = 'battles/battles_list.html'
    template_name = 'battles/battles_list_react.html'
    context_object_name = 'battles_created'

    def get_queryset(self):
        return Battle.objects.filter(creator=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['battles_invited'] = Battle.objects.filter(opponent=self.request.user)
        return context


class CreateBattleView(LoginRequiredMixin, generic.CreateView):
    model = Battle
    template_name = 'battles/create_battle.html'
    form_class = CreateBattleForm

    def get_initial(self):
        return {'creator': self.request.user.id}

    def get_success_url(self):
        return reverse_lazy('battles:details', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        self.object.save()
        send_battle_invite_email(self.object)
        return super().form_valid(form)


class BattleView(LoginRequiredMixin, UserIsPartOfBattleMixin, generic.DetailView):
    model = Battle
    # template_name = 'battles/battle.html'
    template_name = 'battles/battle_react.html'
    context_object_name = 'battle'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creators_pokemons'] = Pokemon.objects.filter(
            battle_team__battle_related=self.object,
            battle_team__trainer=self.object.creator
        )
        context['opponents_pokemons'] = Pokemon.objects.filter(
            battle_team__battle_related=self.object,
            battle_team__trainer=self.object.opponent
        )
        context['user_is_opponent'] = self.object.opponent == self.request.user
        context['user_has_chosen_a_team'] = Pokemon.objects.filter(
            battle_team__battle_related=self.object,
            battle_team__trainer=self.request.user
        ).exists()
        return context


class PokemonListAPIView(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated():
            return Pokemon.objects.none()

        qs = Pokemon.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

    def get_selected_result_label(self, item):
        return item.name

    def get_result_label(self, item):  # noqa
        return format_html('<img src="{}"> {}', item.sprite, item.name)


class ChoosePokemonTeamView(LoginRequiredMixin, UserIsPartOfBattleMixin, generic.CreateView):
    template_name = 'battles/choose_team.html'
    form_class = ChooseTeamForm
    model = Battle  # due to UserIsPartOfBattleMixin.test_func.get_object

    def get_success_url(self):
        return reverse_lazy('battles:list')

    def get(self, request, *args, **kwargs):
        battle_pk = kwargs['pk']
        battle_team = BattleTeam.objects.filter(
            battle_related__pk=battle_pk, trainer=request.user)
        if battle_team.exists():
            messages.error(request, 'You already chose a team!')
            return HttpResponseRedirect(reverse_lazy('battles:details', kwargs={'pk': battle_pk}))
        return super().get(request, *args, **kwargs)

    def get_initial(self):
        return {
            'trainer': self.request.user,
            'battle_related': Battle.objects.get(pk=self.kwargs['pk'])
        }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['battle'] = Battle.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        battle_team = form.save()
        battle = battle_team.battle_related
        if process_battle(battle):
            run_battle_task.delay(battle.id)
        return HttpResponseRedirect(self.get_success_url())


class InviteView(LoginRequiredMixin, generic.CreateView):
    form_class = InviteForm
    template_name = 'battles/invite.html'
    success_url = reverse_lazy('invite')

    def get_initial(self):
        return {'inviter': self.request.user}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.inviter = self.request.user
        self.object.key = create_invite_key()
        self.object.save()
        messages.success(
            self.request,
            'Thanks for inviting someone, {user}! A battle with you will be created as soon as '
            'they sign up.'.format(user=self.request.user.get_short_name()),
            extra_tags='user-invite'
        )
        send_pokebattle_invite_email(self.object)
        return super().form_valid(form)

templates/battles/battle.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle &middot; {{ battle.creator.get_short_name }} vs. {{ battle.opponent.get_short_name }}{% endblock %}

{% block body %}
<div class="pokebattle-container battle">
    {% include 'battles/includes/battle_status.html' %}
    <h2><span class="battle-id">{{ battle.id }}</span> {{ battle.creator.get_short_name }} vs. {{ battle.opponent.get_short_name }}</h2>
    {% if battle.winner %}    
    <div class="battle-result-label{% if battle.winner == request.user %} user-won{% endif %}">
        <strong>{{ battle.winner.get_short_name }}</strong> won!
    </div>
    {% endif %}
    {% include 'common/generic_message.html' %}
    <section class="pick-team">
        {% if not user_has_chosen_a_team %}
            <a href="{% url 'battles:team' battle.pk %}">Pick my team</a>
        {% endif %}
    </section>
    <section class="battle-pokemons">
        <div class="column creators-pokemons">
        {% if creators_pokemons %}
            {% for pokemon in creators_pokemons %}
                {% include 'battles/includes/pokemon_card.html' %}
            {% endfor %}
        {% endif %}
        </div>
        <div class="column opponents-pokemons">
        {% if opponents_pokemons %}
            {% for pokemon in opponents_pokemons %}
                {% include 'battles/includes/pokemon_card.html' %}
            {% endfor %}
        {% endif %}
        </div>
    </section>
</div>
{% endblock %}

templates/battles/battle_react.html
{% load render_bundle from webpack_loader %}

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Pokebattle &middot; Battle with your friends!{% endblock %}</title>
    <meta name="description" content=".">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% render_bundle 'main' 'css' %}
  </head>

  <body>
    {% block body %}
    <div id="pokebattleContainer"></div>
    {% endblock %}

    {% render_bundle 'main' 'js' 'JQUERY' %}
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    {% render_bundle 'main' 'js' %}
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/battles/battles_list.html
{% extends 'base.html' %}

{% block title %}PokeBattle &middot; Your battles{% endblock %}

{% block body %}
<div class="pokebattle-container">
    {% include 'common/generic_message.html' %}
    <div class="battles-list">
        <div class="battles-created">
            <h4>Battles you created</h4>
            <ul>
                {% for battle in battles_created %} {% include 'battles/includes/battle_list_card.html' %} {% endfor %}
            </ul>
        </div>
        <div class="battles-invited">
            <h4>Battles you were invited</h4>
            <ul>
                {% for battle in battles_invited %} {% include 'battles/includes/battle_list_card.html' %} {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/battles/battles_list_react.html
{% load render_bundle from webpack_loader %}

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}Pokebattle &middot; Battle with your friends!{% endblock %}</title>
    <meta name="description" content=".">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% render_bundle 'main' 'css' %}
  </head>

  <body>
    {% block body %}
    <div id="pokebattleContainer"></div>
    {% endblock %}

    {% render_bundle 'main' 'js' 'JQUERY' %}
    <script src="{% url 'js_reverse' %}" type="text/javascript"></script>
    {% render_bundle 'main' 'js' %}
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/battles/choose_team.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}PokeBattle &middot; Choose your team{% endblock %}

{% block body %}
    <div class="pokebattle-container battle">
        <a href="{% url 'battles:details' battle.pk %}">&laquo; Back to battle</a>
        <h3>{{ battle }}</h3>
        <h2>Choose your Pokemons!</h2>
        <div class="team-form-instruction">
            Remember to use only their ids
        </div>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="form-error">{{ form.non_field_errors }}</div>
            {% endfor %}
            {% for error in form.errors.all %}
                <div class="form-error">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <form method="POST" class="battle-creation-form">
            {% csrf_token %}
            {% render_field form.first_pokemon placeholder=form.first_pokemon.label %}
            {% render_field form.second_pokemon placeholder=form.second_pokemon.label %}
            {% render_field form.third_pokemon placeholder=form.third_pokemon.label %}
            
            <div class="inputs-hidden">
                {% render_field form.battle_related %}
                {% render_field form.trainer %}
            </div>
            <input type="submit" value="Pick my team">
        </form>
    </div>

<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{{ form.media }}
{% endblock %}

templates/battles/create_battle.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle &middot; Battle with someone{% endblock %}

{% block body %}
    <div class="pokebattle-container battle">
        <h2>Pick your Pokemons!</h2>
        <form method="POST" class="battle-creation-form">
            {% csrf_token %}
            {% if form.errors %}
            <div class="message">
                {{ form.errors }}
            </div>
            {% endif %}
            <section class="battle-fields">
                <div class="opponent-submit">
                    <em>Choose your opponent</em>
                    {% render_field form.opponent %}
                    <div style="display: none;">
                        {% render_field form.creator %} 
                    </div>
                    <input type="submit" value="Battle!">
                </div>
            </section>
        </form>
    </div>
{% endblock %}

templates/battles/invite.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}PokeBattle &middot; Battle with someone{% endblock %}

{% block body %}
    <div class="pokebattle-container battle">
        <h2>Invite a user!</h2>
        {% include 'common/generic_message.html' %}
        <form method="POST" class="battle-creation-form">
            {% csrf_token %}
            {% include 'common/form_errors.html' %}
            <section class="battle-fields">
                <div class="opponent-submit {% if form.invitee.errors %}has-error{% endif %}">
                    {% for error in form.invitee.errors %}
                        <div class="small-error">{{ error }}</div>
                    {% endfor %}
                    {% render_field form.invitee placeholder='example@email.com' %}
                    <input type="submit" value="Invite">
                </div>
            </section>
        </form>
    </div>
{% endblock %}