pokebattle/urls.py
from django.conf import settings
from django.conf.urls import include, url  # noqa
from django.contrib import admin
from django.views.generic import TemplateView

import django_js_reverse.views

from battles.views import InviteView


urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^admin/statuscheck/', include('celerybeat_status.urls')),
    url(r'^jsreverse/$', django_js_reverse.views.urls_js, name='js_reverse'),
    url(r'^social/', include('social_django.urls', namespace='social')),

    # Pokebattle
    url(r'^', include('users.urls', namespace='auth')),
    url(r'^$', TemplateView.as_view(template_name='common/index.html'), name='home'),
    url(r'^battles/', include('battles.urls', namespace='battles')),
    url(r'^invite/$', InviteView.as_view(), name='invite'),

    # API
    url(r'api/', include('battles.endpoints_urls', namespace='api-battles')),
    url(r'api/', include('users.endpoints_urls', namespace='api-users')),
    url(r'api/', include('pokemons.endpoints_urls', namespace='api-pokemon')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url

from .views import UserInvitedProcessView, UserLoginView, UserLogoutView, UserSignupView


urlpatterns = [
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),
    url(r'^signup/$', UserSignupView.as_view(), name='signup'),
    url(r'^invite/validate$', UserInvitedProcessView.as_view(), name='validate-invite')
]

common/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from model_utils.fields import AutoCreatedField, AutoLastModifiedField


class IndexedTimeStampedModel(models.Model):
    created = AutoCreatedField(_('created'), db_index=True)
    modified = AutoLastModifiedField(_('modified'), db_index=True)

    class Meta:
        abstract = True

templates/common/form_errors.html
{% if form.errors %}
<section class="form-errors">
    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
</section>
{% endif %}

templates/common/generic_message.html
<div class="message-container">
{% if messages %}
    {% for message in messages %}
        <li class="message{% if message.tags %} {{ message.tags }}{% endif %}">{{ message }}</li>
    {% endfor %}
{% endif %}
</div>

templates/common/header.html
{% load staticfiles %}
<header>
    <nav class="navbar">
        <div class="header">
            <a href="{% url 'home' %}">PokeBattle</a>
        </div>
        <div class="menu">
            {% if user.is_authenticated %}
                <a href="{% url 'battles:list' %}">
                    My battles
                </a>
                <a href="/battles/create">
                    Battle with someone
                </a>
                <a href="{% url 'invite' %}">
                    Invite a user
                </a>
                <span class="name">
                    Hello, <strong>{{ user.get_short_name }}</strong>!
                </span>
                <a href="{% url 'auth:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'auth:login' %}">Login/Signup</a>
            {% endif %}
        </div>
    </nav>
</header>

templates/common/index.html
{% extends 'base.html' %}
{% block title %}PokeBattle &middot; Battle with your friends!{% endblock %}

{% block body %}
    <div class="pokebattle-container">
        Hello world.
    </div>
{% endblock %}